# Load a model

Each model has been developed within a class in the folder models. The name of the 
module represent the name of the dataset. The model contains a class for each architecture.
The constructor of the calss build the model, split the dataset and set all the hyperparameters of the networks.
So the reproducibility is achived by only instanziating the model.


First you have to chose a model and a dataset.  

for instacne: GIN on the GRID dataset

In [1]:
MODEL = "GIN"
DATASET = "BA_2grid_house"

# import the model
from models.models_BA_2grid_house import GIN_framework as framework
# import the dataset
from Datasets.synthetics import BA_2grid_house

In [ ]:
# inizialize the framework
dataset = BA_2grid_house()
gnn = framework(dataset,device="cpu")

c:\Users\tomdu\OneDrive\Documents\ENSC_VU\4A-Vu\Thesis\Probing GNN\ProbingVenv\lib\site-packages\torch_geometric\data\in_memory_dataset.py:300: UserWarning: It is not recommended to directly access the internal storage format `data` of an 'InMemoryDataset'. If you are absolutely certain what you are doing, access the internal storage via `InMemoryDataset._data` instead to suppress this warning. Alternatively, you can access stacked individual attributes of every graph via `dataset.{attr_name}`.
  warnings.warn(msg)


In [ ]:
# the gnn object contains the train test split and the model.

print(gnn.model)
print(gnn.train_idx)
print(gnn.dataset[gnn.train_idx])

Net(
  (mlp1): Linear(in_features=10, out_features=30, bias=True)
  (conv1): GINConv(nn=Linear(in_features=10, out_features=30, bias=True))
  (mlp2): Linear(in_features=30, out_features=30, bias=True)
  (conv2): GINConv(nn=Linear(in_features=30, out_features=30, bias=True))
  (lin1): Linear(in_features=30, out_features=30, bias=True)
  (lin2): Linear(in_features=30, out_features=2, bias=True)
)
tensor([ 701, 1225,   47,  ...,   40,  423,  494])
BA_2grid_house(1600)


In [ ]:
# right now the model has random weights.
print(gnn.model.mlp1.weight[0])

tensor([-0.1212, -0.0306,  0.2503,  0.0236, -0.1754,  0.0293,  0.2900,  0.2228,
        -0.2381, -0.1020], dtype=torch.float64, grad_fn=<SelectBackward0>)


In [ ]:
#now that the model is instaziated, we have to load the weights
gnn.load_model("models/"+DATASET+"_"+MODEL)
print("we loaded the weights")
# right now the model has trained weights.
print(gnn.model.mlp1.weight[0])

we loaded the weights
tensor([-0.1264, -0.0357,  0.2452,  0.0184, -0.1806,  0.0242,  0.2849,  0.2177,
        -0.2432, -0.1072], dtype=torch.float64, grad_fn=<SelectBackward0>)


In [ ]:
# we also have a build in function to evaluate the model
gnn.evaluate()

Test Loss: 0.035, Train Acc: 0.971 Test Acc: 0.973


In [ ]:
# we can also train the model for 20 epochs
gnn.train() #gnn.train()

for i in range(20):
    gnn.train()

In [ ]:
gnn.evaluate()

Test Loss: 0.035, Train Acc: 0.971 Test Acc: 0.973


In [ ]:
#save
gnn.save_model("models/"+DATASET+"_"+MODEL)

model saved in:  models/BA_2grid_house_GIN


### GAT on grid-house

In [2]:
DATASET = "BA_2grid_house_with_node_degree_as_features_and_expand_10_dimensions"
MODEL = "GAT"

In [3]:
from models.models_BA_2grid_house import GAT_Framework_5 as GAT_framework
from Datasets.synthetics import BA_2grid_house_with_node_degree_as_features_and_expand_10_dimensions

# inizialize the framework
dataset = BA_2grid_house_with_node_degree_as_features_and_expand_10_dimensions()
gnn = GAT_framework(dataset,device="cpu")

# the gnn object contains the train test split and the model.

print(gnn.model)
print(gnn.train_idx)
print(gnn.dataset[gnn.train_idx])


Net(
  (conv1): GATConv(10, 128, heads=8)
  (conv2): GATConv(1024, 128, heads=8)
  (conv3): GATConv(1024, 128, heads=8)
  (lin1): Linear(in_features=1024, out_features=20, bias=True)
  (lin2): Linear(in_features=20, out_features=2, bias=True)
)
tensor([ 701, 1225,   47,  ...,   40,  423,  494])
BA_2grid_house_with_node_degree_as_features_and_expand_10_dimensions(1600)


c:\Users\tomdu\OneDrive\Documents\ENSC_VU\4A-Vu\Thesis\Probing GNN\ProbingVenv\lib\site-packages\torch_geometric\data\in_memory_dataset.py:300: UserWarning: It is not recommended to directly access the internal storage format `data` of an 'InMemoryDataset'. If you are absolutely certain what you are doing, access the internal storage via `InMemoryDataset._data` instead to suppress this warning. Alternatively, you can access stacked individual attributes of every graph via `dataset.{attr_name}`.
  warnings.warn(msg)


In [4]:
gnn.train() 

0.6942403936386108

In [5]:
#let's train the model
gnn.iterate()


INFO:root:Epoch: 020, Loss: 0.538, Train Loss: 0.553, Train Acc: 0.734, Test Loss: 0.603, Test Acc: 0.710
INFO:root:Epoch: 040, Loss: 0.497, Train Loss: 0.416, Train Acc: 0.807, Test Loss: 0.451, Test Acc: 0.792
INFO:root:Epoch: 060, Loss: 0.234, Train Loss: 0.193, Train Acc: 0.921, Test Loss: 0.237, Test Acc: 0.902
INFO:root:Epoch: 080, Loss: 0.176, Train Loss: 0.211, Train Acc: 0.916, Test Loss: 0.214, Test Acc: 0.915
INFO:root:Epoch: 100, Loss: 0.066, Train Loss: 0.067, Train Acc: 0.983, Test Loss: 0.109, Test Acc: 0.963
INFO:root:Epoch: 120, Loss: 0.047, Train Loss: 0.050, Train Acc: 0.988, Test Loss: 0.097, Test Acc: 0.968


In [7]:
gnn.evaluate()

INFO:root:Train Loss: 0.050, Train Acc: 0.988, Test Loss: 0.097, Test Acc: 0.968


In [6]:
# we can also save the model

gnn.save_model("models/"+DATASET+"_"+MODEL)

INFO:root:Model saved in: models/BA_2grid_house_with_node_degree_as_features_and_expand_10_dimensions_GAT


### Gat 2

In [1]:
DATASET = "BA_2grid_house"
MODEL = "GAT3"

In [1]:
from models.models_BA_2grid_house import GATV2Framework
from Datasets.synthetics import BA_2grid_house

# inizialize the framework
dataset = BA_2grid_house()
gnn = GATV2Framework(dataset,device="cpu")

# the gnn object contains the train test split and the model.

print(gnn.model)
print(gnn.train_idx)
print(gnn.dataset[gnn.train_idx])

Net(
  (conv1): GATv2Conv(10, 10, heads=1)
  (conv2): GATv2Conv(10, 20, heads=1)
  (conv3): GATv2Conv(20, 10, heads=1)
  (lin1): Linear(in_features=10, out_features=20, bias=True)
  (lin2): Linear(in_features=20, out_features=2, bias=True)
)
tensor([ 701, 1225,   47,  ...,   40,  423,  494])
BA_2grid_house(1600)


c:\Users\tomdu\OneDrive\Documents\ENSC_VU\4A-Vu\Thesis\Probing GNN\ProbingVenv\lib\site-packages\torch_geometric\data\in_memory_dataset.py:300: UserWarning: It is not recommended to directly access the internal storage format `data` of an 'InMemoryDataset'. If you are absolutely certain what you are doing, access the internal storage via `InMemoryDataset._data` instead to suppress this warning. Alternatively, you can access stacked individual attributes of every graph via `dataset.{attr_name}`.
  warnings.warn(msg)


In [8]:
#let's train the model
gnn.train()
#gnn.iterate()

0.693176969145371

In [9]:
gnn.evaluate()

INFO:root:Train Loss: 0.693, Train Acc: 0.500, Test Loss: 0.693, Test Acc: 0.500


Using the code to train and load GAT for the GRID dataset

In [1]:
from models.models_BA_2grid import GAT2_framework
from Datasets.synthetics import BA_2grid

# inizialize the framework
dataset = BA_2grid()
gnn = GAT2_framework(dataset,device="cpu")

# the gnn object contains the train test split and the model.

print(gnn.model)
print(gnn.train_idx)
print(gnn.dataset[gnn.train_idx])



Net(
  (conv1): GATConv(10, 30, heads=1)
  (conv2): GATConv(30, 30, heads=1)
  (conv3): GATConv(30, 30, heads=1)
  (lin1): Linear(in_features=30, out_features=10, bias=True)
  (lin2): Linear(in_features=10, out_features=2, bias=True)
)
tensor([ 701, 1225,   47,  ...,   40,  423,  494])
BA_2grid(1600)


c:\Users\tomdu\OneDrive\Documents\ENSC_VU\4A-Vu\Thesis\Probing GNN\ProbingVenv\lib\site-packages\torch_geometric\data\in_memory_dataset.py:300: UserWarning: It is not recommended to directly access the internal storage format `data` of an 'InMemoryDataset'. If you are absolutely certain what you are doing, access the internal storage via `InMemoryDataset._data` instead to suppress this warning. Alternatively, you can access stacked individual attributes of every graph via `dataset.{attr_name}`.
  warnings.warn(msg)


In [13]:
#let's train the model

gnn.iterate()



Epoch: 020, Loss: 0.693, Test Loss: 0.173, Train Acc: 0.500 Test Acc: 0.500
Epoch: 040, Loss: 0.693, Test Loss: 0.173, Train Acc: 0.500 Test Acc: 0.500
Epoch: 060, Loss: 0.693, Test Loss: 0.173, Train Acc: 0.500 Test Acc: 0.500
Epoch: 080, Loss: 0.693, Test Loss: 0.173, Train Acc: 0.500 Test Acc: 0.500
Epoch: 100, Loss: 0.693, Test Loss: 0.173, Train Acc: 0.500 Test Acc: 0.500
Epoch: 120, Loss: 0.693, Test Loss: 0.173, Train Acc: 0.500 Test Acc: 0.500
Epoch: 140, Loss: 0.693, Test Loss: 0.173, Train Acc: 0.500 Test Acc: 0.500
Epoch: 160, Loss: 0.693, Test Loss: 0.173, Train Acc: 0.500 Test Acc: 0.500
Epoch: 180, Loss: 0.693, Test Loss: 0.173, Train Acc: 0.500 Test Acc: 0.500
Epoch: 200, Loss: 0.693, Test Loss: 0.173, Train Acc: 0.500 Test Acc: 0.500
Epoch: 220, Loss: 0.693, Test Loss: 0.173, Train Acc: 0.500 Test Acc: 0.500
Epoch: 240, Loss: 0.693, Test Loss: 0.173, Train Acc: 0.500 Test Acc: 0.500
Epoch: 260, Loss: 0.693, Test Loss: 0.173, Train Acc: 0.500 Test Acc: 0.500
Epoch: 280, 

KeyboardInterrupt: 

In [11]:
gnn.evaluate()

Test Loss: 0.173, Train Acc: 0.500 Test Acc: 0.500


In [12]:
# we can also save the model
gnn.save_model("models/"+DATASET+"_"+MODEL)

NameError: name 'DATASET' is not defined

GAT on grid

In [ ]:
DATASET = "grid"
MODEL = "GAT"

from models.models_BA_2grid import GAT_framework
from Datasets.grid import Grid

# Initialize the framework
dataset = Grid()
gnn = GAT_framework(dataset, device="cpu")

# The gnn object contains the train test split and the model.
print(gnn.model)
print(gnn.train_idx)
print(gnn.dataset[gnn.train_idx])

# Train the model
gnn.train()

# Evaluate the model
gnn.evaluate()

# Save the model
gnn.save_model("models/" + DATASET + "_" + MODEL)


# RGCN

In [1]:
MODEL = "RGCN"
DATASET = "BA_2grid_house"

# import the model
from models.models_BA_2grid_house import RGCN_framework as framework
# import the dataset
from Datasets.synthetics import BA_2grid_house_with_node_degree_as_features_and_expand_10_dimensions
# inizialize the framework
dataset = BA_2grid_house_with_node_degree_as_features_and_expand_10_dimensions()
gnn = framework(dataset,device="cpu")
# the gnn object contains the train test split and the model.

print(gnn.model)
print(gnn.train_idx)
print(gnn.dataset[gnn.train_idx])
# right now the model has random weights.


c:\Users\tomdu\OneDrive\Documents\ENSC_VU\4A-Vu\Thesis\Probing GNN\ProbingVenv\lib\site-packages\torch_geometric\data\in_memory_dataset.py:300: UserWarning: It is not recommended to directly access the internal storage format `data` of an 'InMemoryDataset'. The data of the dataset is already cached, so any modifications to `data` will not be reflected when accessing its elements. Clearing the cache now by removing all elements in `dataset._data_list`. If you are absolutely certain what you are doing, access the internal storage via `InMemoryDataset._data` instead to suppress this warning. Alternatively, you can access stacked individual attributes of every graph via `dataset.{attr_name}`.
  warnings.warn(msg)


Net(
  (conv1): RGCNConv(10, 30, num_relations=2)
  (conv2): RGCNConv(30, 30, num_relations=2)
  (lin1): Linear(in_features=30, out_features=30, bias=True)
  (lin2): Linear(in_features=30, out_features=2, bias=True)
)
tensor([ 701, 1225,   47,  ...,   40,  423,  494])
BA_2grid_house_with_node_degree_as_features_and_expand_10_dimensions(1600)


In [2]:
gnn.iterate()

INFO:root:Epoch: 020, Loss: 0.476, Train Loss: 0.470, Train Acc: 0.766, Test Loss: 0.510, Test Acc: 0.728
INFO:root:Epoch: 040, Loss: 0.415, Train Loss: 0.410, Train Acc: 0.796, Test Loss: 0.442, Test Acc: 0.775
INFO:root:Epoch: 060, Loss: 0.397, Train Loss: 0.391, Train Acc: 0.798, Test Loss: 0.424, Test Acc: 0.782
INFO:root:Epoch: 080, Loss: 0.386, Train Loss: 0.380, Train Acc: 0.809, Test Loss: 0.414, Test Acc: 0.785
INFO:root:Epoch: 100, Loss: 0.378, Train Loss: 0.373, Train Acc: 0.811, Test Loss: 0.409, Test Acc: 0.795
INFO:root:Epoch: 120, Loss: 0.371, Train Loss: 0.365, Train Acc: 0.824, Test Loss: 0.402, Test Acc: 0.805
INFO:root:Epoch: 140, Loss: 0.367, Train Loss: 0.361, Train Acc: 0.829, Test Loss: 0.400, Test Acc: 0.805
INFO:root:Epoch: 160, Loss: 0.363, Train Loss: 0.357, Train Acc: 0.830, Test Loss: 0.398, Test Acc: 0.805
INFO:root:Epoch: 180, Loss: 0.359, Train Loss: 0.352, Train Acc: 0.831, Test Loss: 0.396, Test Acc: 0.800
INFO:root:Epoch: 200, Loss: 0.354, Train Loss:

In [3]:
#save
gnn.save_model("models/"+DATASET+"_"+MODEL)

INFO:root:Model saved in: models/BA_2grid_house_RGCN


In [5]:
#now that the model is instaziated, we have to load the weights
gnn.load_model("models/"+DATASET+"_"+MODEL)
print("we loaded the weights")
# right now the model has trained weights.
gnn.evaluate()


INFO:root:Model loaded from: models/BA_2grid_house_RGCN
INFO:root:Train Loss: 0.303, Train Acc: 0.846, Test Loss: 0.368, Test Acc: 0.823


we loaded the weights
